TEST VERITABANINIZDA EMPLOYEE ISIMLI SÜTUN BILGILERI ID(INTEGER), NAME VARCHAR(50), BIRTHDAY DATE, EMAIL VARCHAR(100) OLAN BIR TABLO OLUŞTURALIM.
CREATE TABLE EMPLOYEE (
ID SERIAL PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(100),
BIRTHDAY DATE);
OLUŞTURDUĞUMUZ EMPLOYEE TABLOSUNA 'MOCKAROO' SERVISINI KULLANARAK 50 ADET VERI EKLEYELIM.
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('KALINA', 'KWILLMORE0@STATE.TX.US', '2009-04-02');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('GODDART', 'GLISTONE1@INSTAGRAM.COM', '1968-11-01');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('WINIFRED', 'WDEI2@VKONTAKTE.RU', '1942-07-02');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('BERTY', 'BSINGLETON3@NATIONALGEOGRAPHIC.COM', '1938-02-23');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('NATA', 'NREVANCE4@WORDPRESS.ORG', '1955-12-06');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('BRANNON', 'BISGAR5@ICIO.US', '2005-01-29');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('LULA', 'LEMMINS6@WIKIA.COM', '1901-04-23');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('BOBBY', 'BHELLYER7@REDIFF.COM', '1935-02-08');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('SHELBI', 'SNOLLEAU8@INTEL.COM', '1940-11-17');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('TESSIE', 'TDILLINGSTONE9@ARTISTEER.COM', '1962-08-27');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('GUIDO', 'GGUNBIEA@SHINYSTAT.COM', '2016-05-05');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('EVITA', 'EBRADWELLB@JIGSY.COM', '1922-09-25');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('ILYSA', 'IMULVEYC@WILEY.COM', '1960-05-07');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('CHIARRA', 'CKEMISHD@NAROD.RU', '1920-01-27');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('EVANGELINA', 'EWOOLASTONE@ELEGANTTHEMES.COM', '1915-06-29');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('LIVVYY', 'LCREVAGHF@GITHUB.COM', '1908-05-29');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('CHELSAE', 'CPOULSTONG@FACEBOOK.COM', '1940-07-20');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('NOELLA', 'NMENENDEZH@GIZMODO.COM', '1960-06-23');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('JARID', 'JDIPIETROI@CMU.EDU', '1982-06-28');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('KRISTI', 'KOMALLEYJ@DMOZ.ORG', '1985-11-18');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('ALONZO', 'AURLINGK@NYTIMES.COM', '1958-11-01');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('ARLEEN', 'APETTYL@SALON.COM', '2003-05-17');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('HERSHEL', 'HANGRICKM@GEOCITIES.COM', '1927-07-05');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('HOBIE', 'HNOULTONN@WSJ.COM', '1985-12-28');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('HOPE', 'HTHOMSONO@CHRON.COM', '2006-06-09');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('ERNESTA', 'EGRIMSTEADP@MAC.COM', '1980-05-23');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('PEPE', 'PCROCETTIQ@SKYPE.COM', '1980-05-11');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('SPIKE', 'SBREACHERR@ADDTHIS.COM', '1909-11-22');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('ALMIRA', 'AKARELS@1688.COM', '2022-07-21');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('ANITA', 'APABSTT@WEBEDEN.CO.UK', '1942-07-07');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('MALACHI', 'MSHOULERU@VIRGINIA.EDU', '2000-02-11');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('ADRIAN', 'ASALERGV@GOOGLE.COM', '1912-08-26');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('ANTONINA', 'ABONIFASW@WORDPRESS.COM', '1931-09-25');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('DESIRAE', 'DDRACKFORDX@REDCROSS.ORG', '2018-07-22');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('IVONNE', 'IJOHNESY@BIBLEGATEWAY.COM', '1974-05-11');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('ALFONSO', 'AGAREYZ@FASTCOMPANY.COM', '2009-04-26');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('ZARLA', 'ZWHEBELL10@YELLOWBOOK.COM', '1968-01-26');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('CYNDIE', 'CGARNER11@DISCOVERY.COM', '2012-05-14');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('CLAIR', 'CMCCOMBE12@YOUTU.BE', '1979-06-04');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('HORST', 'HBRIXEY13@BLOGGER.COM', '1941-07-09');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('NANNETTE', 'NPETTIS14@NEWYORKER.COM', '1983-03-04');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('THIBAUT', 'TRAYWOOD15@AMAZON.CO.JP', '2021-01-12');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('RIVY', 'RWHITEBREAD16@REVERBNATION.COM', '1921-01-23');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('DARYA', 'DJZAK17@PHPBB.COM', '1926-10-11');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('LALO', 'LBASFORD18@BANDCAMP.COM', '1928-09-18');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('SHEELA', 'SGRUBBE19@GOOGLE.COM.HK', '1999-06-09');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('DUNSTAN', 'DCATLIN1A@HATENA.NE.JP', '1983-04-06');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('PADDIE', 'PVUITTET1B@ARIZONA.EDU', '1991-08-12');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('BRANDYN', 'BWESTWOOD1C@SOGOU.COM', '1919-02-17');
INSERT INTO EMPLOYEE (NAME, EMAIL, BIRTHDAY) VALUES ('RICHART', 'RTROSDALL1D@STATCOUNTER.COM', '1960-06-08');
SELECT * FROM EMPLOYEE
SÜTUNLARIN HER BIRINE GÖRE DIĞER SÜTUNLARI GÜNCELLEYECEK 5 ADET UPDATE IŞLEMI YAPALIM.
UPDATE EMPLOYEE SET NAME='DENIZ' ,EMAIL='DENIZ@FE.CO',BIRTHDAY='1989-05-06' WHERE ID=5
UPDATE EMPLOYEE SET NAME='XXX' WHERE NAME LIKE 'A%'
UPDATE EMPLOYEE SET NAME='SILA' WHERE BIRTHDAY>'1998-07-08'
UPDATE EMPLOYEE SET NAME='CEZA' WHERE EMAIL LIKE '%EDU'
UPDATE EMPLOYEE SET NAME='ÖRNEK' WHERE ID=36
SELECT * FROM EMPLOYEE
DELETE FROM EMPLOYEE WHERE ID=24 
DELETE FROM EMPLOYEE WHERE NAME LIKE 'C%'
DELETE FROM EMPLOYEE WHERE BIRTHDAY='1999-06-09'
DELETE FROM EMPLOYEE WHERE ID=45
DELETE FROM EMPLOYEE WHERE ID=12



